In [7]:
import pandas as pd

xls = pd.read_excel("../inputs/regular NBA.xlsx")

In [8]:
xls

,1,2,3,4,5,6,7,8,9,10,...,44,45,46,47,48,49,50,51,52,53
0,Player,Team,Age,GP,W,L,Min,PTS,FGM,FGA,...,PIE,POSS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shai Gilgeous-Alexander,OKC,26,76,63,13,34.2,2485,859,1657,...,19.9,5514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anthony Edwards,MIN,23,79,48,31,36.3,2180,719,1612,...,14,5883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nikola Jokić,DEN,30,70,46,24,36.7,2072,784,1365,...,20.6,5471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Giannis Antetokounmpo,MIL,30,67,40,27,34.2,2037,791,1320,...,21,4772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,Mac McClung,ORL,26,2,1,1,5.1,0,0,2,...,0,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,Terence Davis,SAC,28,1,1,0,7.9,0,0,2,...,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,Terry Taylor,SAC,25,3,1,2,2.1,0,0,1,...,4.3,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,Riley Minix,SAS,24,1,0,1,6.8,0,0,1,...,3.9,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
569,Jalen McDaniels,WAS,27,4,2,2,1.8,0,0,0,...,11.4,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
xls.shape

(570, 53)

In [13]:
xls.duplicated().sum()

np.int64(0)

In [18]:
xls = pd.ExcelFile("../inputs/regular NBA.xlsx")
for sheet in xls.sheet_names:
    df = pd.read_excel("../inputs/regular NBA.xlsx", sheet_name=sheet)

    print("\n" + "="*50)
    print(sheet)
    print("="*50)

    print(df.columns.tolist())
    print(df.head())

==================================================
Données NBA
==================================================
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]
                        1     2    3   4   5   6     7     8    9     10  ...  \
0                   Player  Team  Age  GP   W   L   Min   PTS  FGM   FGA  ...
1  Shai Gilgeous-Alexander   OKC   26  76  63  13  34.2  2485  859  1657  ...
2          Anthony Edwards   MIN   23  79  48  31  36.3  2180  719  1612  ...
3             Nikola Jokić   DEN   30  70  46  24  36.7  2072  784  1365  ...
4    Giannis Antetokounmpo   MIL   30  67  40  27  34.2  2037  791  1320  ...

     44    45  46  47  48  49  50  51  52  53
0   PIE  POSS NaN NaN NaN NaN NaN NaN NaN NaN
1  19.9  5514 NaN NaN NaN NaN NaN NaN NaN NaN
2    14  5883 NaN NaN NaN NaN NaN NaN NaN NaN
3  20.6  5471 NaN NaN NaN NaN NaN NaN NaN NaN
4    21  4772 NaN NaN NaN NaN NaN NaN NaN NaN

[5 rows x 53 columns]

==================================================
Analyse
==================================================
['Analyse de la saison de NBA', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']
  Analyse de la saison de NBA               Unnamed: 1  \
0                         NaN                      NaN
1                         NaN                      NaN
2                         NaN                      NaN
3                         NaN                      NaN
4                        Code  Nom complet de l'équipe

                    Unnamed: 2                        Unnamed: 3 Unnamed: 4  \
0                          NaN                               NaN        NaN
1                          NaN                               NaN        NaN
2                          NaN                               NaN        NaN
3                          NaN                               NaN        NaN
4  Nombre de joueur par équipe  Nombre de point total par équipe        NaN

  Unnamed: 5 Unnamed: 6 Unnamed: 7
0        NaN        NaN        NaN
1        NaN        NaN        NaN
2        NaN        NaN        NaN
3        NaN        NaN        NaN
4        NaN        NaN        NaN

==================================================
Analyse Vide
==================================================
['Analyse de la saison de NBA', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']
  Analyse de la saison de NBA               Unnamed: 1  \
0                         NaN                      NaN
1                         NaN                      NaN
2                         NaN                      NaN
3                         NaN                      NaN
4                        Code  Nom complet de l'équipe

                    Unnamed: 2                        Unnamed: 3 Unnamed: 4  \
0                          NaN                               NaN        NaN
1                          NaN                               NaN        NaN
2                          NaN                               NaN        NaN
3                          NaN                               NaN        NaN
4  Nombre de joueur par équipe  Nombre de point total par équipe        NaN

  Unnamed: 5 Unnamed: 6 Unnamed: 7
0        NaN        NaN        NaN
1        NaN        NaN        NaN
2        NaN        NaN        NaN
3        NaN        NaN        NaN
4        NaN        NaN        NaN

==================================================
Equipe
==================================================
['Code', "Nom complet de l'équipe"]
  Code Nom complet de l'équipe
0  ATL           Atlanta Hawks
1  BKN           Brooklyn Nets
2  BOS          Boston Celtics
3  CHA       Charlotte Hornets
4  CHI           Chicago Bulls

==================================================
Dictionnaire des données
==================================================
['Dictionnaire des données', 'Unnamed: 1']
  Dictionnaire des données                                         Unnamed: 1
0                   Player                                      Nom du joueur
1                     Team                Équipe du joueur (code à 3 lettres)
2                      Age                                      Âge du joueur
3                       GP              Nombre de matchs joués (Games Played)
4                        W  Nombre de victoires de l'équipe lors des match...

In [19]:
df

   Dictionnaire des données                                         Unnamed: 1
0                    Player                                      Nom du joueur
1                      Team                Équipe du joueur (code à 3 lettres)
2                       Age                                      Âge du joueur
3                        GP              Nombre de matchs joués (Games Played)
4                         W  Nombre de victoires de l'équipe lors des match...
5                         L                                 Nombre de défaites
6                       Min                  Minutes moyennes jouées par match
7                       PTS                Points marqués en moyenne par match
8                       FGM          Tirs réussis par match (Field Goals Made)
9                       FGA      Tirs tentés par match (Field Goals Attempted)
10                      FG%                   Pourcentage de réussite aux tirs
11                 15:00:00                  Minutes jouées après 15:00 de jeu
12                      3PA                   Tirs à 3 points tentés par match
13                      3P%                 Pourcentage de réussite à 3 points
14                      FTM          Lancers francs réussis (Free Throws Made)
15                      FTA                              Lancers francs tentés
16                      FT%         Pourcentage de réussite aux lancers francs
17                     OREB                                  Rebonds offensifs
18                     DREB                                  Rebonds défensifs
19                      REB                                     Rebonds totaux
20                      AST                         Passes décisives (Assists)
21                      TOV                         Balles perdues (Turnovers)
22                      STL                             Interceptions (Steals)
23                      BLK                                   Contres (Blocks)
24                       PF                                Fautes personnelles
25                       FP                                     Fantasy Points
26                      DD2  Double-doubles (≥10 dans deux catégories princ...
27                      TD3  Triple-doubles (≥10 dans trois catégories prin...
28                    + / -  Plus-Minus (écart de score lorsque le joueur e...
29                   OFFRTG  Offensive Rating (points marqués par 100 posse...
30                   DEFRTG  Defensive Rating (points encaissés par 100 pos...
31                   NETRTG                       Net Rating = OFFRTG - DEFRTG
32                     AST%  Pourcentage d'assists – implication dans les p...
33                   AST/TO                     Ratio passes / pertes de balle
34                AST RATIO               Ratio d’assists pour 100 possessions
35                    OREB%  Pourcentage de rebonds offensifs parmi ceux di...
36                    DREB%                                   Idem en défensif
37                     REB%  Pourcentage de rebonds totaux parmi ceux dispo...
38                 TO RATIO  Turnover Ratio – pertes de balle par 100 posse...
39                     EFG%      Effective Field Goal % (pondère les 3 points)
40                      TS%  True Shooting % (inclut FG et FT dans l'effica...
41                     USG%  Usage Rate – % des actions utilisées par le jo...
42                     PACE         Rythme de jeu (possessions par 48 minutes)
43                      PIE  Player Impact Estimate – évaluation globale de...
44                     POSS                 Nombre total de possessions jouées

In [20]:
df.columns.tolist()

['Dictionnaire des données', 'Unnamed: 1']

In [21]:
df.head()

  Dictionnaire des données                                         Unnamed: 1
0                   Player                                      Nom du joueur
1                     Team                Équipe du joueur (code à 3 lettres)
2                      Age                                      Âge du joueur
3                       GP              Nombre de matchs joués (Games Played)
4                        W  Nombre de victoires de l'équipe lors des match...